# action.yml
name: 'Resolint-CI-Action'
description: 'Conduct Resolint checks on a component of an AADL model'
inputs:
  component-to-analyze:  # id of input
    description: '**Required** The name of the AADL component to implementation analyze.'
    required: true
    default: 'Top.impl'
  output-path:
    description: '**Required** The absolute output path for the JSON formatted results.'
    required: true
    default: 'Top.impl'
  workspace-location: # dir of workspace
    description: 'The path to the workspace containing the AADL projects (equivalent to -path option for headless Eclipse).'
    required: false
    default: '.'
  project-path:
    description: 'The path, relative to the workspace location, to the directory containing the AADL project.'
    required: false
    default: '.'
  validation-only:
    description: 'Perform syntax validation only.'
    required: false
    default: 'false'
  return-passing-results:
    description: 'Return passing Resolint results.'
    required: false
    default: 'false'
  exit-on-warning:
    description: 'Terminate analysis on warnings as well as errors.'
    required: false
    default: 'false'
  supplementaty-aadl:
    description: 'A space-delimited list of absolute paths to additional AADL files outside the workspace project.'
    required: false
    default: ''
  rulesets:
    description: 'A space-delimited list of ruleset names.'
    required: false
    default: ''
outputs:
  timestamp:
    description: 'The date/time that the analysis was completed'
  status:
    description: 'Summary of analysis completion status'
  status-messages: 
    description: 'Description of analysis completion status'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workspace-location }}
    - ${{ inputs.component-to-analyze }}
    - ${{ inputs.project-path }}
    - ${{ inputs.output-path }}
    - ${{ inputs.validation-only }}
    - ${{ inputs.csv-output }}
    - ${{ inputs.exit-on-warning }}
    - ${{ inputs.supplementary-aadl }}
